const RESOURCE_STATUSES = [
  'AVAILABLE',
  'ASSIGNED',
  'EN_ROUTE',
  'ON_SITE',
  'TRANSPORTING',
  'RETURNING'
];

const RESOURCE_TYPES = [
  'AMBULANCE_VAN',
  'RESCUE_BOAT',
  'HELICOPTER',
  'POWER_GENERATOR_TRUCK'
];

const IDEMPOTENCY_STATUSES = [
  'PROCESSING',
  'COMPLETED'
];

const TRANSPORT_TYPES = [
  'SHELTER_EVACUATION'
];

module.exports = {
  IDEMPOTENCY_STATUSES,
  RESOURCE_STATUSES,
  RESOURCE_TYPES,
  TRANSPORT_TYPES
};
